// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-classes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/data/demo.ts
var classes = [
  {
    id: "psych101",
    name: "Intro to Psychology",
    professor: "Dr. Martinez",
    location: "Harmon Hall 204",
    days: ["Mon", "Wed", "Fri"],
    time: "10:00 AM",
    color: "bg-primary",
    currentTopic: "Memory & Learning",
    nextExamDate: "2026-04-11",
    readiness: 62,
    suggestedAction: "Review lecture 7 flashcards",
    gradingWeights: [
      { category: "Exams", weight: 40 },
      { category: "Quizzes", weight: 20 },
      { category: "Papers", weight: 25 },
      { category: "Participation", weight: 15 }
    ],
    chapters: [
      { number: 1, title: "Foundations of Psychology", status: "completed" },
      { number: 2, title: "Research Methods", status: "completed" },
      { number: 3, title: "Biological Bases of Behavior", status: "completed" },
      { number: 4, title: "Sensation & Perception", status: "completed", notes: "Focus on signal detection theory", professorHints: [{ id: "ph1", text: "Professor said this will be on the exam \u2014 know the difference between sensation and perception", tag: "exam-hint", pinned: true, createdAt: "2026-03-20" }] },
      { number: 5, title: "States of Consciousness", status: "in-progress", notes: "Currently reviewing sleep stages", professorHints: [{ id: "ph2", text: "Review slides 15-20 for sleep cycle details", tag: "class-reminder", createdAt: "2026-04-01" }] },
      { number: 6, title: "Memory & Learning", status: "not-started", aiBreakdown: { bigIdea: "How we encode, store, and retrieve information", keyTerms: ["Encoding", "Short-term memory", "Long-term memory", "Retrieval cues", "Mnemonics"], professorCares: "Understanding the multi-store model and being able to apply encoding strategies", confusing: "The difference between recall and recognition; interference theory", practiceNext: "Practice identifying encoding types in everyday situations" } },
      { number: 7, title: "Cognition & Intelligence", status: "not-started" }
    ]
  },
  {
    id: "bio200",
    name: "Biology II",
    professor: "Dr. Chen",
    location: "Science Center 112",
    days: ["Tue", "Thu"],
    time: "9:00 AM",
    color: "bg-success",
    currentTopic: "Cell Division & Genetics",
    nextExamDate: "2026-04-18",
    readiness: 78,
    suggestedAction: "Complete practice problems on mitosis",
    gradingWeights: [
      { category: "Exams", weight: 50 },
      { category: "Labs", weight: 30 },
      { category: "Homework", weight: 20 }
    ],
    chapters: [
      { number: 1, title: "Cell Structure", status: "completed" },
      { number: 2, title: "Cell Membrane & Transport", status: "completed" },
      { number: 3, title: "Cellular Respiration", status: "completed" },
      { number: 4, title: "Photosynthesis", status: "completed" },
      { number: 5, title: "Cell Division", status: "in-progress", professorHints: [{ id: "ph3", text: "Know all phases of mitosis AND meiosis \u2014 he compares them on exams", tag: "exam-hint", pinned: true, createdAt: "2026-03-28" }] },
      { number: 6, title: "Genetics", status: "not-started" }
    ]
  },
  {
    id: "eng102",
    name: "English Composition II",
    professor: "Prof. Williams",
    location: "Liberal Arts 308",
    days: ["Mon", "Wed"],
    time: "1:00 PM",
    color: "bg-accent",
    currentTopic: "Argumentative Essays",
    nextExamDate: "",
    readiness: 45,
    suggestedAction: "Start brainstorming for Essay 3",
    gradingWeights: [
      { category: "Essays", weight: 60 },
      { category: "Discussion Posts", weight: 20 },
      { category: "Peer Reviews", weight: 10 },
      { category: "Participation", weight: 10 }
    ],
    chapters: [
      { number: 1, title: "Rhetorical Analysis", status: "completed" },
      { number: 2, title: "Research Methods", status: "completed" },
      { number: 3, title: "Argumentative Writing", status: "in-progress", professorHints: [{ id: "ph4", text: "Focus on essay structure \u2014 she values clear topic sentences", tag: "assignment-note", createdAt: "2026-03-30" }, { id: "ph5", text: "Citation style must be MLA. She docks points for APA.", tag: "class-reminder", pinned: true, createdAt: "2026-03-25" }] },
      { number: 4, title: "Synthesis Essays", status: "not-started" }
    ]
  },
  {
    id: "math150",
    name: "College Algebra",
    professor: "Dr. Patel",
    location: "Math Building 101",
    days: ["Mon", "Wed", "Fri"],
    time: "8:00 AM",
    color: "bg-warning",
    currentTopic: "Polynomial Functions",
    nextExamDate: "2026-04-09",
    readiness: 34,
    suggestedAction: "Catch up on Chapter 4 homework",
    gradingWeights: [
      { category: "Exams", weight: 45 },
      { category: "Homework", weight: 30 },
      { category: "Quizzes", weight: 15 },
      { category: "Final", weight: 10 }
    ],
    chapters: [
      { number: 1, title: "Functions & Graphs", status: "completed" },
      { number: 2, title: "Linear Functions", status: "completed" },
      { number: 3, title: "Quadratic Functions", status: "completed", professorHints: [{ id: "ph6", text: "He hinted at quadratic formula problems on the midterm", tag: "exam-hint", pinned: true, createdAt: "2026-03-15" }] },
      { number: 4, title: "Polynomial Functions", status: "in-progress", notes: "Need to catch up on homework", aiBreakdown: { bigIdea: "Understanding polynomial behavior through degree, zeros, and end behavior", keyTerms: ["Degree", "Leading coefficient", "Zeros", "Multiplicity", "End behavior", "Synthetic division"], professorCares: "Ability to graph polynomials by hand and find all real/complex roots", confusing: "Polynomial long division and synthetic division steps", practiceNext: "Work through factoring problems in section 4.3" } },
      { number: 5, title: "Rational Functions", status: "not-started" },
      { number: 6, title: "Exponential & Logarithmic", status: "not-started" }
    ]
  }
];
var assignments = [
  {
    id: "a1",
    classId: "eng102",
    className: "English Composition II",
    title: "Argumentative Essay Draft",
    dueDate: "2026-04-07",
    priority: "high",
    estimatedTime: "3 hours",
    status: "started",
    instructions: "Write a 5-page argumentative essay on a social issue of your choice. Use at least 4 scholarly sources. MLA format.",
    professorHints: [{ id: "aph1", text: "She said she'll accept late drafts for half credit if submitted within 24 hours", tag: "assignment-note", createdAt: "2026-04-02" }]
  },
  {
    id: "a2",
    classId: "math150",
    className: "College Algebra",
    title: "Chapter 4 Problem Set",
    dueDate: "2026-04-06",
    priority: "high",
    estimatedTime: "1.5 hours",
    status: "not-started",
    instructions: "Complete problems 1-30 (odd) from Section 4.2 and 4.3."
  },
  {
    id: "a3",
    classId: "psych101",
    className: "Intro to Psychology",
    title: "Reading Response: Chapter 5",
    dueDate: "2026-04-08",
    priority: "medium",
    estimatedTime: "45 minutes",
    status: "not-started",
    instructions: "Write a 1-page response discussing key concepts from Chapter 5. Include personal connections."
  },
  {
    id: "a4",
    classId: "bio200",
    className: "Biology II",
    title: "Lab Report: Osmosis",
    dueDate: "2026-04-10",
    priority: "medium",
    estimatedTime: "2 hours",
    status: "draft-done",
    instructions: "Complete formal lab report for osmosis experiment. Include data tables and analysis."
  },
  {
    id: "a5",
    classId: "eng102",
    className: "English Composition II",
    title: "Discussion Post Week 8",
    dueDate: "2026-04-05",
    priority: "low",
    estimatedTime: "20 minutes",
    status: "not-started",
    instructions: "Post a 200-word response to the weekly reading. Reply to at least 2 classmates."
  }
];
var exams = [
  {
    id: "e1",
    classId: "math150",
    className: "College Algebra",
    title: "Midterm Exam 2",
    date: "2026-04-09",
    readiness: 34,
    topics: ["Quadratic Functions", "Polynomial Functions", "Graphing", "Word Problems"],
    strongAreas: ["Quadratic formula", "Basic graphing"],
    weakAreas: ["Polynomial long division", "Complex roots", "Word problems"],
    professorHints: [{ id: "eph1", text: "Dr. Patel said the exam will emphasize graphing and word problems", tag: "exam-hint", pinned: true, createdAt: "2026-04-01" }]
  },
  {
    id: "e2",
    classId: "psych101",
    className: "Intro to Psychology",
    title: "Exam 2: Chapters 4-6",
    date: "2026-04-11",
    readiness: 62,
    topics: ["Sensation & Perception", "Consciousness", "Memory & Learning"],
    strongAreas: ["Sensation basics", "Sleep stages"],
    weakAreas: ["Memory models", "Learning theories"],
    professorHints: [{ id: "eph2", text: "Dr. Martinez mentioned there will be a lot of application questions \u2014 not just definitions", tag: "exam-hint", createdAt: "2026-04-03" }]
  },
  {
    id: "e3",
    classId: "bio200",
    className: "Biology II",
    title: "Unit 3 Exam",
    date: "2026-04-18",
    readiness: 78,
    topics: ["Cellular Respiration", "Photosynthesis", "Cell Division"],
    strongAreas: ["Cellular respiration steps", "Photosynthesis overview"],
    weakAreas: ["Mitosis vs Meiosis details"]
  }
];
var workShifts = [
  { id: "w1", day: "Mon", startTime: "5:00 PM", endTime: "9:00 PM", location: "Campus Bookstore" },
  { id: "w2", day: "Wed", startTime: "5:00 PM", endTime: "9:00 PM", location: "Campus Bookstore" },
  { id: "w3", day: "Fri", startTime: "12:00 PM", endTime: "5:00 PM", location: "Campus Bookstore" },
  { id: "w4", day: "Sat", startTime: "10:00 AM", endTime: "4:00 PM", location: "Campus Bookstore" }
];
var calendarEvents = (() => {
  const events = [];
  classes.forEach((c) => {
    c.days.forEach((day) => {
      const hour = parseInt(c.time);
      const isPM = c.time.includes("PM") && hour !== 12;
      const h = isPM ? hour + 12 : hour;
      events.push({ id: `cal-${c.id}-${day}`, day, startHour: h, duration: 1, label: c.name, type: "class", linkedId: c.id, linkedRoute: `/classes/${c.id}` });
    });
  });
  workShifts.forEach((s) => {
    const startH = parseInt(s.startTime);
    const isPM = s.startTime.includes("PM") && startH !== 12;
    const endH = parseInt(s.endTime);
    const endPM = s.endTime.includes("PM") && endH !== 12;
    const start = isPM ? startH + 12 : startH;
    const end = endPM ? endH + 12 : endH;
    events.push({ id: `cal-${s.id}`, day: s.day, startHour: start, duration: end - start, label: "Work", type: "work" });
  });
  return events;
})();

// src/lib/mcp/tools/list-classes.ts
var list_classes_default = defineTool({
  name: "list_classes",
  title: "List classes",
  description: "List the student's current classes with professor, meeting time, current topic, next exam date, and readiness score.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const rows = classes.map((c) => ({
      id: c.id,
      name: c.name,
      professor: c.professor,
      location: c.location,
      meets: `${c.days.join("/")} ${c.time}`,
      currentTopic: c.currentTopic,
      nextExamDate: c.nextExamDate,
      readiness: c.readiness,
      suggestedAction: c.suggestedAction
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { classes: rows }
    };
  }
});

// src/lib/mcp/tools/list-upcoming.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_upcoming_default = defineTool2({
  name: "list_upcoming_deadlines",
  title: "List upcoming deadlines",
  description: "List upcoming assignments and exams within the given number of days (default 14). Includes class name, due date, priority, and readiness.",
  inputSchema: {
    days: z.number().int().min(1).max(120).optional().describe("Look-ahead window in days. Defaults to 14.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ days }) => {
    const window = days ?? 14;
    const now = Date.now();
    const cutoff = now + window * 24 * 60 * 60 * 1e3;
    const asg = assignments.filter((a) => {
      const t = Date.parse(a.dueDate);
      return !Number.isNaN(t) && t >= now && t <= cutoff;
    }).map((a) => ({
      kind: "assignment",
      id: a.id,
      title: a.title,
      className: a.className,
      dueDate: a.dueDate,
      priority: a.priority,
      status: a.status
    }));
    const exm = exams.filter((e) => {
      const t = Date.parse(e.date);
      return !Number.isNaN(t) && t >= now && t <= cutoff;
    }).map((e) => ({
      kind: "exam",
      id: e.id,
      title: e.title,
      className: e.className,
      dueDate: e.date,
      readiness: e.readiness,
      weakAreas: e.weakAreas
    }));
    const combined = [...asg, ...exm].sort(
      (a, b) => Date.parse(a.dueDate) - Date.parse(b.dueDate)
    );
    return {
      content: [
        {
          type: "text",
          text: combined.length ? JSON.stringify(combined, null, 2) : `No deadlines in the next ${window} days.`
        }
      ],
      structuredContent: { windowDays: window, items: combined }
    };
  }
});

// src/lib/mcp/tools/get-class-intelligence.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
var get_class_intelligence_default = defineTool3({
  name: "get_class_intelligence",
  title: "Get class intelligence",
  description: "Return peer-aggregated 'high-yield' topics for a class: probability of appearing on the next exam, confidence band, and student engagement. Use `list_classes` to discover valid classId values.",
  inputSchema: {
    classId: z2.string().min(1).describe("Class id, e.g. 'psych101'."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max topics to return. Default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ classId, limit }) => {
    const cls = classes.find((c) => c.id === classId);
    if (!cls) {
      return {
        content: [{ type: "text", text: `Unknown classId: ${classId}` }],
        isError: true
      };
    }
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return {
        content: [{ type: "text", text: "Backend is not configured." }],
        isError: true
      };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("topic_scores").select("topic_name,probability,confidence_band,student_count,miss_rate,star_count").eq("class_id", classId).order("probability", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const summary = {
      class: { id: cls.id, name: cls.name, professor: cls.professor },
      topics: data ?? []
    };
    return {
      content: [
        {
          type: "text",
          text: (data ?? []).length ? JSON.stringify(summary, null, 2) : `No peer intelligence available yet for ${cls.name}.`
        }
      ],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "norsaaoyppctrvxxgjtg";
var mcp_default = defineMcp({
  name: "campus-companion-mcp",
  title: "Campus Companion",
  version: "0.1.0",
  instructions: "Tools for Campus Companion, an AI academic OS for college students (ADHD-friendly). Use `list_classes` to discover the student's current classes and readiness. Use `list_upcoming_deadlines` for assignments and exams coming due. Use `get_class_intelligence` for peer-aggregated high-yield topics on a specific class. All tools are read-only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_classes_default, list_upcoming_default, get_class_intelligence_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
