// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSupabaseNetworkFetch } from '@/lib/demo/supabaseNetworkPolicy';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabaseNetworkFetch = createSupabaseNetworkFetch({ supabaseUrl: SUPABASE_URL });

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: supabaseNetworkFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Fail closed until the permanent production domain and Supabase RP ID are ready.
    experimental: { passkey: import.meta.env.VITE_PASSKEYS_ENABLED === "true" },
  }
});
